### ISSUE TITLE
Cannot access normal image context menu

### ISSUE THREAD

**Issue by teo1978** [lokesh/lightbox2#524] opened 2016-06-26 00:22 UTC
When you are viewing an image enlarged with LightBox, and you right-click on the image, the usual items like **"save image"** or **"open image in new tab"** don't come up in the context menu. This is because there's a div on top of the image, so you are right-clicking on it rather than on the image.

This is extremely annoying and kills standard usability features for no good reason.

**Comment by teo1978** [comment] 2016-07-03 19:40
I've come up with a workaround for this, which is to apply the following stile **after lightbox.css**:
```css
.lb-image {
	border: solid 1px #888;
}

.lb-nav {
	position: static;
	overflow: visible;
	width: 0;
	height: 0;
}
.lb-nav a.lb-next {
	float: none;
	position: absolute;
	top: 0;
	right: 0;
	width: 25%;
	min-width: 60px;
}
.lb-nav a.lb-prev {
	float: none;
	position: absolute;
	top: 0;
	left: 0;
	width: 25%;
	min-width: 60px;
}
```

**Comment by lokesh** [comment] 2016-10-29 05:19
The lack of original context/right-click menu to save images has always bugged me as well. I decided to investigate the issue today.

The way I solved it is to listen for right mouse button down event on the `div` on top of the image and then quickly set the pointer-events to none so that when the mouseup and right-click events do occur the div is not listening and the event continues bubbling down through to the image.

Fix is incoming in the next version.

**Comment by lokesh** [comment] 2016-10-29 05:43
https://github.com/lokesh/lightbox2/commit/363c3cb8af8fae1b6f95d6679df976022290f878

Changes will go out in next release.

**Closed** 2016-10-29 05:43 UTC
Labels: reviewed

**Comment by teo1978** [comment] 2016-10-29 09:35
Seems a very poor solution to me. 
Isn't it much better to just not have a huge div on top of the image in the first place??

I have done that. I attach the modified version I produced in case it may be of any help. Unfortunately, it's mixed with some unrelated changes, some of which destroy features that I didn't need (for example, I got rid of animations). Also I modified the compiled js directly. But if you take a diff between v.2.8.2 and mine and have a look, you may be able to isolate the part that addresses this issue. I'm not entirely sure, though, if it is compatible with maintaining your approach to not fixing #533 (it should be pretty orthogonal to that, but I don't remember for sure).

[lightbox2_modified.zip](https://github.com/lokesh/lightbox2/files/559862/lightbox2_modified.zip)

Oh, there's also this piece of CSS that I applied on top of it. Most of it should be irrelevant to the issue at hand, but in case you quickly try my version "out of the box", it would probably give unexpected results without it
```
.lb-outerContainer {
	background-color: transparent;
}
.lb-outerContainer, .lb-dataContainer, .lb-container, .lightbox .lb-image {
	border-radius: 0;
	-moz-border-radius-bottomleft: 0;
	-webkit-border-bottom-left-radius: 0;
	border-bottom-left-radius: 0;
	-moz-border-radius-bottomright: 0;
	-webkit-border-bottom-right-radius: 0;
	border-bottom-right-radius: 0;
}
.lb-image {
	border: solid 1px #888;
}


.lb-nav a.lb-prev, .lb-nav a.lb-next {
	-webkit-transition: initial;
	-moz-transition: initial;
	-o-transition: initial;
	transition: initial;
}
```

**Comment by lokesh** [comment] 2016-10-30 16:40
@teo1978 The solution I have added https://github.com/lokesh/lightbox2/commit/363c3cb8af8fae1b6f95d6679df976022290f878 is a bit of a hack but it works well for desktop users w/mice. It doesn't adversely affect mobile touch users.

The ideal desktop solution, also a bit of a hack, but cleaner, would be to have the nav items be small and matching the size of their icons. So right-clicking the nav items would show the contextmenu for the icons and right-clicking anywhere else on the image would show the image's contextmenu. Then a mousemove event listener would be added to the image and we would detect which section of the image the mouse pointer is on and then use that data to apply a class to a parent that would be used to show/hide the specific nav arrow as required. On clicking the image, we would also check the mouse pointer position so we can determine if the prev or next action would be fired.

The problem is that this would be a breaking change so I am not planning anything this drastic in v2.x.

**Comment by scottieGGGG** [comment] 2019-11-13 21:32
Not sure when exactly, but the work-around / hack is no longer working :-(
As of Chrome v78.0.3904.97, while right click show the context menu, the Copy Image is not capturing the image data and putting in clipboard.  But it works in IE.
