### ISSUE TITLE
How do i make a swipe next image or prev image

### ISSUE THREAD

**Issue by kurodz** [lokesh/lightbox2#356] opened 2014-12-04 17:01 UTC
As title , swipe function like this ? 

this.$lightbox.find('.lightbox').on('swiperight', function() {
        if (self.currentImageIndex === 0) {
          self.changeImage(self.album.length - 1);
        } else {
          self.changeImage(self.currentImageIndex - 1);
        }
        return false;
      });

**Comment by lokesh** [comment] 2015-07-09 18:31
Dupe of #233

**Closed by lokesh** 2015-07-09 18:31 UTC

**Comment by super-summer** [comment] 2016-07-11 03:43
这个swiperight还要引入jquery mobile 文件，
