### ISSUE TITLE
Compatibility magento 1.9.4

### ISSUE THREAD

**Issue by lmpampaletakis** [lokesh/lightbox2#695] opened 2020-10-03 20:55 UTC
Hi I cannot find compatibility with magento 1.9.4.

**Comment by Alphatone** [comment] 2020-11-02 10:59
@lmpampaletakis Could you elaborate on your issue? I am working on a magento 1.9.3 project right now and I am having troubles as well.

**Comment by maryfranharper** [comment] 2021-01-10 21:11
Duplicate of #

**Closed** 2023-02-21 18:54 UTC
