### ISSUE TITLE
title with link - css problem

### ISSUE THREAD

**Issue by eliz82** [lokesh/lightbox2#536] opened 2016-07-26 12:16 UTC
Hey Lokesh 
I'm a developer, I have made program that can generate html lightbox2 code . My program also have an option to generate titles with links. My generated code is something like this:
`<a href="http://piwigo.org/demo/_data/i/upload/2016/06/21/20160621161901-690d078f-me.jpg" data-lightbox="id172" data-title="<a target='_blank' href='http://piwigo.org/demo/picture.php?/1546'>Chevaux de Camargue</a>"><img class="alignleft" src="http://piwigo.org/demo/_data/i/upload/2016/06/21/20160621161901-690d078f-sq.jpg" /></a>`
When the lightbox2 title is linked the color transform to white into dark blue. Very hard to see on a semi-transparent dark background.
The visited link is even worse. It's dark grey. You can barely see it. See attached print screen.
![clipboard01](https://cloud.githubusercontent.com/assets/1497398/17136623/276a43d8-533f-11e6-945e-1d288e77622e.jpg)

I personally can insert one or two lines at my end of lightbox.css file and fix the problem
`.lb-caption a { color: #fff !important; }`
but if the users use the official version or a CDN version or a lightbox.css minified , I cannot ask all users to make this modification for the Lightbox2 with linked title to be usable.
So please also modify the official version.

**Comment by lokesh** [comment] 2016-10-25 18:49
By default the caption link should use the color that is set as your default `a` color.

![lightbox](https://cloud.githubusercontent.com/assets/51469/19699654/02cd1f9e-9aa9-11e6-9bc2-b721662b18f2.png)

Closing as this is not a bug.

**Comment by eliz82** [comment] 2016-10-26 06:40
> By default the caption link should use the color that is set as your default a color.
:(
NO, not a god idea! The "a" color of lightbox2 caption should be something visible against lightbox2 default dark background. And I can explain you why.

Because default "a" color on the page **can be** something dark/gray especially if the page background is a light color (like white). Your example with "a" default color on page being light blue on a white background is a happy coincidence.

They are thousands of wordpress themes out there, some users of my wordpress plugin that loading lightbox2 from a CDN **may have bad luck** and have a wordpress theme with dark "a" default color.

You must think this from the end users perspective, some wordpress users may not have skills to make css modifications to their theme, or some developers may use CDN to load lightbox2 in the page (
https://cdnjs.com/libraries/lightbox2 / http://www.jsdelivr.com/projects/lightbox2 ) you will force them to use local versions of lightbox2 and manually modify your lightbox.css to add a ".lb-caption a" specification.

**Comment by lokesh** [comment] 2016-10-27 05:06
@eliz82 thanks for the follow-up and the details. You make some good points. I'll review solutions today.

**Comment by lokesh** [comment] 2016-10-29 16:09
Per your suggestions I'm updating the default to link color in Lightbox captions. I'm defaulting a light blue similar to the default blue link color:
```
.lb-data .lb-caption a {
  color: #4ae;
}
``
![image](https://cloud.githubusercontent.com/assets/51469/19831128/6727b722-9db7-11e6-8225-be5b299cdb33.png)

Thanks again for all the feedback!

**Closed by lokesh** 2016-10-29 16:09 UTC
Labels: review

**Comment by eliz82** [comment] 2016-10-31 05:54
> I'm defaulting to a light blue similar to the default blue link color.
it's ok.
