### ISSUE TITLE
Disable Scrolling scrolls to top when image is clicked.

### ISSUE THREAD

**Issue by wreighsantos** [lokesh/lightbox2#620] opened 2018-02-03 16:38 UTC
Why does clicking the image to open the modal **scrolls** the page to the top when `disableScrolling`  is **true**?

To produce the following bug, go to [Lightbox Examples](http://lokeshdhakar.com/projects/lightbox2/#examples), open the console, and enter the following.

    lightbox.option({ disableScrolling: true });

Then before clicking an image, scroll so that you're not at the top of the page but you should still see the image (so you could click it tho).

After clicking, you can see that the modal opens but the page **scrolls** up, leaving the modal down there! Are there other things that I should do when implementing `disableScrolling`?

**Comment by jrpeters89** [comment] 2018-03-28 05:01
It looks like the class ".lb-disable-scrolling" is the issue. I commented out the "position: fixed;" attribute and it seems to be working fine now on desktop. The author put a note in here though saying position: fixed is required for iOS. I haven't tested on that yet.

```
html.lb-disable-scrolling {
  overflow: hidden;
  /* Position fixed required for iOS. Just putting overflow: hidden; on the body is not enough. */
  //position: fixed;
  height: 100vh;
  width: 100vw;
}
```

**Comment by spdivn** [comment] 2018-10-14 17:12
```
html.lb-disable-scrolling {
  overflow: hidden;
  position: static;
  height: 100vh;
  width: 100vw;
}
```

position static work in iOS device and you can't scroll.

**Comment by SimranMalhotra** [comment] 2018-12-11 15:41
Just add this script to disable scrolling in lighbox
  
`  <script>
        lightbox.option({
    disableScrolling:true
    })
    </script>`

**Comment by lokesh** [comment] 2019-04-22 04:44
Should be fixed in v2.11.0: https://github.com/lokesh/lightbox2/releases/tag/v2.11.0

Please reopen if issue persists for anyone.

**Closed by lokesh** 2019-04-22 04:44 UTC
Labels: [status] pending release, [type] bug

**Comment by rajjanorkar** [comment] 2019-08-13 16:13
This is still an issue in 2.11.1 version. When first image is clicked it is scrolling top.

**Comment by kevinlo123** [comment] 2019-09-03 21:08
There is a bug when using this package on IE11. When anchor element is clicked the screen jumps to the top of the page. This issue was found using browserstack to test website on IE11 windows. I also tested on http://lokeshdhakar.com/projects/lightbox2/#examples to make sure it just wasnt the website im working on and same issue persists.

**Comment by lokesh** [comment] 2019-09-04 00:08
More info: https://github.com/lokesh/lightbox2/issues/667#issuecomment-527642372

Does this issue happen irregardless of the `disableScrolling` value? I'm going to use browserstack and verify later this week, in-transit for a bit.

**Comment by rajjanorkar** [comment] 2019-09-04 00:21
Yes, either true or false.

For me i can replicate on latest Google chrome and Firefox

**Comment by eding42** [comment] 2019-11-18 23:35
Yeah, can also reproduce on chrome and firefox.

**Comment by tristonb2049** [comment] 2019-11-19 01:26
I am having trouble with this issue as well still. Even when set to true, it will still scroll to top on iPhone safari use.

**Comment by alexeichemenda** [comment] 2020-06-13 02:42
I encountered the same issue while playing with the latest version, and I noticed that:
 this happens only when I set the resizeDuration to 0. (during all of my tests, I had the disableScrolling = true option).

Hope this helps you find the issue @lokesh !

**Comment by emmasax4** [comment] 2020-07-11 16:57
Yes this is an issue for me as well. However, the default of `resizeDuration` should already be set to 700, per the Options in [the documentation](https://lokeshdhakar.com/projects/lightbox2/#options). I tried setting the `resizeDuration` to `1` just to see if that fixed it, and it looks like it does not.

@lokesh The issue is also on the examples as well, so I think it's reproducible on almost every browser.

Thing to note is that it doesn't happen _every_ time I open the image. The best way for me to see it is to open fresh a page, scroll to the image straight away, and then click the problematic image right away.

**Comment by theHacker** [comment] 2020-08-15 12:20
> Thing to note is that it doesn't happen _every_ time I open the image. The best way for me to see it is to open fresh a page, scroll to the image straight away, and then click the problematic image right away.

This describes it very good.

I am having the issue on a Chromium browser (v84.0.4147.105) and with `disableScrolling` left to default `false`.
Since I do not like animations on my websites I set options
```
fadeDuration: 1,
imageFadeDuration: 1,
resizeDuration: 1
```
I also tried `disabledScrolling = true`. You can reproduce the issue with this setting as well. After clicking an image, the page scrolls top, so you don't see the Lightbox, but then you can't scroll down again. - So `disabledScrolling` seems completely indepedent of this issue.

The solution in https://github.com/lokesh/lightbox2/issues/667 seems to help.
Commenting out `self.$overlay.focus();` trashes keyboard navigation (I really don't care :-)), but it seems to "fix" the issue.

**Comment by ashok-2695** [comment] 2021-11-24 20:37
Just Add below line to your  lightbox-plus-jquery.min.js 

`lightbox.option({ disableScrolling: true });`

![Capture4](https://user-images.githubusercontent.com/94541917/143309726-baf8cb9d-d4c3-4670-8fec-553b2aa320f9.JPG)

**Comment by alexis-clavicle** [comment] 2025-02-03 08:12
@jrpeters89 https://lnkr.fun/6e2bfc5
