### ISSUE TITLE
Lightbox 2 / White container not framing whole image

### ISSUE THREAD

**Issue by chasdevlin** [lokesh/lightbox2#333] opened 2014-10-14 15:17 UTC
Lightbox v2.7.1
![lb](https://cloud.githubusercontent.com/assets/9216610/4631359/fcb60f0e-53b4-11e4-8932-0be576e375ad.png)
The white outer-container doesn't cover bottom and right edges of image - but this occurs randomly and specific to Chrome. IE looks fine.

Refreshing the page sometimes fixes it. But it's not correct all the time. Very odd. Is there a fix or css setting I'm missing? Thanks!

http://adsausage.com/fancybox4.html

**Comment by Sebirlinem** [comment] 2015-01-16 02:25
I found this happened with Chrome when all images in a delta-lightbox group have exactly the same delta-title. Dosn't occur for groups with only a single image.

Could be fixed by changing or removing the delta-title from at least one of the images in the group.

**Comment by savalo** [comment] 2015-01-27 16:53
I solved same problem today, but I need similar look like old version, with white border and with background under image title, there is css:

.lb-outerContainer {
  /*  border */
  padding:10px;
  border-bottom-right-radius:0;
  border-bottom-left-radius:0; 
}
.lb-container {
  padding: 0;
}
.lb-dataContainer {
  background-color: white;
  padding:0 10px;
}
.lb-data {
  padding: 0 4px;
  color: #444;
}

**Closed** 2015-06-16 04:44 UTC

**Comment by tstavinoha** [comment] 2015-11-19 19:30
This bug is still active in v2.8.1. Everything exactly as described in first two posts. IE works fine, no problemin FF as well. Public demo app works in Chrome, but the overflow appears in a custom site (Bootstrap, React, Webpack, ...).

It is connected to calculation of height and width of elements. Size of the displayed image is relative to the size of the container padding. When lightbox sets up, it reads padding sizes using jquery and stores them for later use.

The problem is that Chrome reports padding size as 0 until the lightbox is first displayed. By that time, the zeroes are cached and that's that. I don't know, it's wierd.

**Comment by erezgreenberg** [comment] 2016-08-08 16:57
This is an old post but thought I'd let you guys know that I had same issue and it was due to the lightbox CSS stylesheet being AFTER the lightbox JS script on the page. As soon as I moved the CSS to BEFORE the JS it worked

**Comment by lokesh** [comment] 2016-10-27 06:21
Thanks @erezgreenberg

I was able to recreate the issue as well by moving the `lightbox.css` loading after the `lightbox.js` script load and execution.
