### ISSUE TITLE
bower.js jQuery requirement

### ISSUE THREAD

**Issue by lwrbakro** [lokesh/lightbox2#600] opened 2017-09-29 11:29 UTC
Is this compatible with jQuery 3.*?

**Comment by szepeviktor** [comment] 2017-10-04 16:19
Duplicate of #582

**Comment by lokesh** [comment] 2017-11-26 03:22
Closing because it is a dupe of #582.

Fix is queued up for a release this week. Currently in `dev` branch.

PR: https://github.com/lokesh/lightbox2/pull/614

**Closed by lokesh** 2017-11-26 03:22 UTC
