### ISSUE TITLE
Multi-row gallery makes lightbox go outside viewport

### ISSUE THREAD

**Issue by TheLukaBoss** [lokesh/lightbox2#676] opened 2020-03-18 16:35 UTC
Please see the site at [jbc.lnps.co.uk/gallery.html](jbc.lnps.co.uk/gallery.html), and please respect my privacy/my client's privacy by not navigating elsewhere. It works best on computers, I am working on making it mobile friendly. Using Chrome on Windows. Not tested if issue occurs on mobile.

I am loading in images from a JSON file (the JS creates elements on the page), with a max of 3 images per row. This is my config:
```
lightbox.option({
    'resizeDuration': 250,
    'disableScrolling': true,
    'fitImagesInViewport': true
})
```
As you can see from the image below, the image goes off the screen. However, if I remove the second row, the issue does not occur.

![image](https://user-images.githubusercontent.com/58115698/76984429-bb50b300-6936-11ea-8324-e17abf8f0ed0.png)

Can you please explain what I may be doing wrong?

Thanks for a great JS library, looking forward to V3!

**Comment by shaques** [comment] 2020-03-21 08:42
I have this problem as well. Is it something we're doing wrong?

![image](https://user-images.githubusercontent.com/61057237/77222928-c7fc2380-6b4f-11ea-99fa-6a14b1de4193.png)

**Comment by lokesh** [comment] 2020-05-10 03:52
Closing out older issues.

Sorry I didn't get to this in time, but I haven't seen this issue in my local testing so I am assuming it related to the setup and was not a bug with the library itself. Possibly an issue w/the conflicting CSS on the page?

If this issue still persists for anyone, please post on https://stackoverflow.com/ with details about your scenario and I and others can help. Thanks.

**Closed by lokesh** 2020-05-10 03:52 UTC

**Comment by titantwentyone** [comment] 2020-08-04 14:55
Closed issue but experienced the same issue. Ensuring you have the doctype in your html helped me:

`<!DOCTYPE html>`
